#!/usr/bin/env bash

function clean ()
{
  rm -f *.tar.gz
}

function main ()
{
  startingDir=$PWD
  while [ ! -d ".git" ]; do
    cd ..
  done

  declare -A diffMap
  gitDiffs=$(git diff --name-only)
  for i in $gitDiffs; do
    topLevelDir=$(echo "$i" | cut -d "/" -f 1)
    diffMap[$topLevelDir]="${diffMap[$topLevelDir]} $i"
  done

  for i in "${!diffMap[@]}"; do
    tarballDir="$i-$(date +%Y%m%d).tar.gz"
    tar czf $tarballDir ${diffMap[$i]}
    if [ $PWD != "$startingDir" ]; then
      mv $tarballDir $startingDir/$tarballDir
    fi
  done
}

if declare -f "$1" > /dev/null; then
  "$@"
else
  main
fi

